In [35]:
import numpy as np
import geopy
import pandas as pd
import math

In [2]:
infers1 = pd.read_csv('output_yolo_infer1_horizon_0.csv')
infers2 = pd.read_csv('output_yolo_infer1_horizon_180.csv')
infers3 = pd.read_csv('output_yolo_infer1_vertical_270.csv')
infers4 = pd.read_csv('output_yolo_infer1_vertical_90.csv')
infers5 = pd.read_csv('output_yolo_infer2_horizon_0.csv')
infers6 = pd.read_csv('output_yolo_infer2_horizon_180.csv')
infers7 = pd.read_csv('output_yolo_infer2_vertical_270.csv')
infers8 = pd.read_csv('output_yolo_infer2_vertical_90.csv')

In [3]:
from uszipcode import SearchEngine, SimpleZipcode, Zipcode
search = SearchEngine()

def csv_par(df):
    for i in range(len(df)):
        df.loc[i, 'lat'] = float(df.loc[i, 'imgname'].split('-')[0])
        df.loc[i, 'long'] = float(df.loc[i, 'imgname'].split('-')[2]) * -1.0
        df.loc[i, 'angle'] = df.loc[i, 'imgname'].split('-')[3][:-4]
        result = search.by_coordinates(df.loc[i, 'lat'], df.loc[i, 'long'], radius=3)
        df.loc[i, 'zipcode'] = result[0].zipcode
        df.loc[i, 'lat'] = df.loc[i, 'lat'].astype(float).round(4)
        df.loc[i, 'long'] = df.loc[i, 'long'].astype(float).round(4)
    return df

In [4]:
# 7/1 save df by zipcode in csv
def zip_df(df):
    for i in df["zipcode"].unique():
        temp_df = df[df["zipcode"] == i]
        temp_df.to_csv(i + '.csv', encoding = 'utf-8', index = False)

In [5]:
output1 = csv_par(infers1)

In [9]:
output2 = csv_par(infers2)
output3 = csv_par(infers3)
output4 = csv_par(infers4)
output5 = csv_par(infers5)
output6 = csv_par(infers6)
output7 = csv_par(infers7)
output8 = csv_par(infers8)

In [48]:
final_df = pd.concat([output1, output2, output3, output4, output5, output6, output7, output8], ignore_index=True)

In [49]:
len(final_df)

17614

In [50]:
len(final_df["zipcode"].unique())

18

In [54]:
zip_df(final_df)

In [55]:
final_df["class"].unique()

array([3, 2, 0, 4, 1])

In [28]:
pm = pd.read_csv('parking_meters.csv')
# class 0- lamp, class 1- sign-h, class 2- fh, class 3-nopark, class 4-stop, class 5- pm
pm_ff = pd.DataFrame(columns=['LATITUDE', 'LONGITUDE', 'ZIPCODE', 'CLASS'])
for i in range(len(pm)):
    result = search.by_coordinates(pm.loc[i, 'LATITUDE'], pm.loc[i, 'LONGITUDE'], radius=1)
    pm_ff.loc[i, 'LATITUDE'] = pm.loc[i, 'LATITUDE']
    pm_ff.loc[i, 'LONGITUDE'] = pm.loc[i, 'LONGITUDE']
    pm_ff.loc[i, 'ZIPCODE'] = result[0].zipcode
    pm_ff.loc[i, 'CLASS'] = 5

In [29]:
pm_ff

     LATITUDE LONGITUDE ZIPCODE CLASS
0     39.7395  -104.982   80264     5
1     39.7401  -104.958   80206     5
2      39.731  -104.987   80203     5
3     39.7433  -104.983   80264     5
4     39.7352  -104.989   80264     5
...       ...       ...     ...   ...
6139  39.7431  -104.994   80264     5
6140  39.7515      -105   80202     5
6141  39.7393  -105.007   80204     5
6142  39.7317  -104.935   80206     5
6143  39.7399  -104.964   80218     5

[6144 rows x 4 columns]

In [31]:
pm_ff['LATITUDE'] = pm_ff['LATITUDE'].astype(float).round(4)

In [33]:
pm_ff['LONGITUDE'] = pm_ff['LONGITUDE'].astype(float).round(4)

In [34]:
pm_ff.to_csv('parking_meter_zip99.csv', encoding='utf-8', index=False)

In [35]:
infers = pd.read_csv('downtown_2500Img.csv')

In [36]:
infers

,imgname,class,confidence,xcenter,ycenter,width,hight
0,39.74061978--104.9893416-315.jpg,0,1,0.335156,0.454688,0.032813,0.412500
1,39.74061978--104.9893416-315.jpg,0,1,0.471094,0.580469,0.039062,0.192188
2,39.74528706--104.99208540000001-315.jpg,0,1,0.410156,0.421875,0.045312,0.637500
3,39.74528706--104.99208540000001-315.jpg,0,1,0.762500,0.392969,0.121875,0.748437
4,39.74528706--104.99208540000001-315.jpg,3,1,0.771094,0.543750,0.029687,0.040625
...,...,...,...,...,...,...,...
3472,39.75705913--104.97513719999999-315.jpg,0,1,0.939063,0.417969,0.121875,0.610937
3473,39.75023775--105.0047976-315.jpg,0,1,0.543750,0.503906,0.096875,0.229688
3474,39.74060365--104.99289809999999-315.jpg,0,1,0.442969,0.530469,0.020313,0.107812
3475,39.75009--105.0046024-135.jpg,0,1,0.924219,0.539062,0.045312,0.131250
3476,39.74099391--104.99646640000002-225.jpg,0,1,0.414844,0.537500,0.026562,0.134375

In [37]:
new_inf = csv_par(infers)

In [38]:
new_inf

,imgname,class,confidence,xcenter,ycenter,width,hight,lat,long,angle,zipcode
0,39.74061978--104.9893416-315.jpg,0,1,0.335156,0.454688,0.032813,0.412500,39.740620,-104.989342,315,80264
1,39.74061978--104.9893416-315.jpg,0,1,0.471094,0.580469,0.039062,0.192188,39.740620,-104.989342,315,80264
2,39.74528706--104.99208540000001-315.jpg,0,1,0.410156,0.421875,0.045312,0.637500,39.745287,-104.992085,315,80264
3,39.74528706--104.99208540000001-315.jpg,0,1,0.762500,0.392969,0.121875,0.748437,39.745287,-104.992085,315,80264
4,39.74528706--104.99208540000001-315.jpg,3,1,0.771094,0.543750,0.029687,0.040625,39.745287,-104.992085,315,80264
...,...,...,...,...,...,...,...,...,...,...,...
3472,39.75705913--104.97513719999999-315.jpg,0,1,0.939063,0.417969,0.121875,0.610937,39.757059,-104.975137,315,80205
3473,39.75023775--105.0047976-315.jpg,0,1,0.543750,0.503906,0.096875,0.229688,39.750238,-105.004798,315,80202
3474,39.74060365--104.99289809999999-315.jpg,0,1,0.442969,0.530469,0.020313,0.107812,39.740604,-104.992898,315,80264
3475,39.75009--105.0046024-135.jpg,0,1,0.924219,0.539062,0.045312,0.131250,39.750090,-105.004602,135,80202
3476,39.74099391--104.99646640000002-225.jpg,0,1,0.414844,0.537500,0.026562,0.134375,39.740994,-104.996466,225,80264

In [41]:
# class 0- lamp, class 1- sign-h, class 2- fh, class 3-nopark, class 4-stop, class 5- pm
infer_ff = pd.DataFrame(columns=['LATITUDE', 'LONGITUDE', 'ZIPCODE', 'CLASS'])
for i in range(len(new_inf)):
    result = search.by_coordinates(new_inf.loc[i, 'lat'], new_inf.loc[i, 'long'], radius=2)
    infer_ff.loc[i, 'LATITUDE'] = new_inf.loc[i, 'lat'].astype(float).round(4)
    infer_ff.loc[i, 'LONGITUDE'] = new_inf.loc[i, 'long'].astype(float).round(4)
    infer_ff.loc[i, 'ZIPCODE'] = result[0].zipcode
    infer_ff.loc[i, 'CLASS'] = new_inf.loc[i, 'class']

In [43]:
infer_ff["LATITUDE"][0]

39.7406

In [44]:
infer_ff.to_csv('downtown99.csv', encoding='utf-8', index=False)

In [6]:
output1

,imgname,class,confidence,xcenter,ycenter,width,hight,lat,long,angle,zipcode
0,39.74879271--105.02297879999999-0.jpg,3,0.436579,0.124219,0.567187,0.045312,0.046875,39.7488,-105.0230,0,80204
1,39.77412428--105.0159814-0.jpg,2,0.887750,0.415625,0.728906,0.034375,0.064062,39.7741,-105.0160,0,80211
2,39.77415137--105.01891609999998-0.jpg,0,0.907404,0.450781,0.499219,0.164062,0.557813,39.7742,-105.0189,0,80211
3,39.77415137--105.01891609999998-0.jpg,2,0.856585,0.860156,0.746094,0.032813,0.054688,39.7742,-105.0189,0,80211
4,39.763224--105.00516359999999-0.jpg,0,0.878048,0.191406,0.372656,0.267188,0.739062,39.7632,-105.0052,0,80211
...,...,...,...,...,...,...,...,...,...,...,...
3077,39.73684731--104.9876376-0.jpg,2,0.713935,0.695312,0.665625,0.018750,0.031250,39.7368,-104.9876,0,80264
3078,39.78216811--105.02622-0.jpg,3,0.503650,0.225781,0.585938,0.020313,0.021875,39.7822,-105.0262,0,80212
3079,39.751205999999996--105.0249996-0.jpg,0,0.811093,0.076563,0.360156,0.150000,0.464063,39.7512,-105.0250,0,80211
3080,39.76752569--105.0514081-0.jpg,0,0.616398,0.290625,0.507031,0.059375,0.351562,39.7675,-105.0514,0,80212
3081,39.72612284--105.0323514-0.jpg,0,0.952682,0.450781,0.437500,0.176563,0.500000,39.7261,-105.0324,0,80219

In [13]:
output7['angle'].unique()

array(['270'], dtype=object)

In [14]:
infers9 = pd.read_csv('downtown_2500img.csv')

In [15]:
output9 = csv_par(infers9)

In [17]:
output9['angle'].unique()

array(['315', '135', '45', '225'], dtype=object)

In [20]:
output9['ycenter'].max()

0.8804687499999999

In [25]:
#7/5 adding columns by bounding box 'xcenter' position [L, C, R]
def csv_par2(df):
    for i in range(len(df)):
        df.loc[i, 'lat'] = float(df.loc[i, 'imgname'].split('-')[0])
        df.loc[i, 'long'] = float(df.loc[i, 'imgname'].split('-')[2]) * -1.0
        df.loc[i, 'angle'] = df.loc[i, 'imgname'].split('-')[3][:-4]
        result = search.by_coordinates(df.loc[i, 'lat'], df.loc[i, 'long'], radius=3)
        df.loc[i, 'zipcode'] = result[0].zipcode
        df.loc[i, 'lat'] = df.loc[i, 'lat'].astype(float).round(4)
        df.loc[i, 'long'] = df.loc[i, 'long'].astype(float).round(4)
        if df.loc[i, 'xcenter'] <= 0.333333:
            df.loc[i, 'detect_loc'] = 'L'
        elif df.loc[i, 'xcenter'] > 0.666666:
            df.loc[i, 'detect_loc'] = 'R'
        else:
            df.loc[i, 'detect_loc'] = 'C'
    return df

In [26]:
new_inf = csv_par2(infers1)

In [27]:
new_inf

,imgname,class,confidence,xcenter,ycenter,width,hight,lat,long,angle,zipcode,detect_loc
0,39.74879271--105.02297879999999-0.jpg,3,0.436579,0.124219,0.567187,0.045312,0.046875,39.7488,-105.0230,0,80204,L
1,39.77412428--105.0159814-0.jpg,2,0.887750,0.415625,0.728906,0.034375,0.064062,39.7741,-105.0160,0,80211,C
2,39.77415137--105.01891609999998-0.jpg,0,0.907404,0.450781,0.499219,0.164062,0.557813,39.7742,-105.0189,0,80211,C
3,39.77415137--105.01891609999998-0.jpg,2,0.856585,0.860156,0.746094,0.032813,0.054688,39.7742,-105.0189,0,80211,R
4,39.763224--105.00516359999999-0.jpg,0,0.878048,0.191406,0.372656,0.267188,0.739062,39.7632,-105.0052,0,80211,L
...,...,...,...,...,...,...,...,...,...,...,...,...
3077,39.73684731--104.9876376-0.jpg,2,0.713935,0.695312,0.665625,0.018750,0.031250,39.7368,-104.9876,0,80264,R
3078,39.78216811--105.02622-0.jpg,3,0.503650,0.225781,0.585938,0.020313,0.021875,39.7822,-105.0262,0,80212,L
3079,39.751205999999996--105.0249996-0.jpg,0,0.811093,0.076563,0.360156,0.150000,0.464063,39.7512,-105.0250,0,80211,L
3080,39.76752569--105.0514081-0.jpg,0,0.616398,0.290625,0.507031,0.059375,0.351562,39.7675,-105.0514,0,80212,L
3081,39.72612284--105.0323514-0.jpg,0,0.952682,0.450781,0.437500,0.176563,0.500000,39.7261,-105.0324,0,80219,C

In [32]:
#7/5 adjusting coordinates by 'xcenter' position [L, C, R]. 0.013 mile = ~20 meters = 0.0002
# currently only accounts for the 0 angle. need to account for 'angle'
def csv_par3(df, delta):
    for i in range(len(df)):
        df.loc[i, 'lat'] = float(df.loc[i, 'imgname'].split('-')[0])
        df.loc[i, 'long'] = float(df.loc[i, 'imgname'].split('-')[2]) * -1.0
        df.loc[i, 'angle'] = df.loc[i, 'imgname'].split('-')[3][:-4]
        result = search.by_coordinates(df.loc[i, 'lat'], df.loc[i, 'long'], radius=3)
        df.loc[i, 'zipcode'] = result[0].zipcode
        df.loc[i, 'lat'] = df.loc[i, 'lat'].astype(float).round(4)
        df.loc[i, 'long'] = df.loc[i, 'long'].astype(float).round(4)
        if df.loc[i, 'xcenter'] <= 0.333333:
            df.loc[i, 'detect_loc'] = 'L'
            df.loc[i, 'new_lat'] = df.loc[i, 'lat'] + delta/2
            df.loc[i, 'new_long'] = df.loc[i, 'long']
        elif df.loc[i, 'xcenter'] > 0.666666:
            df.loc[i, 'detect_loc'] = 'R'
            df.loc[i, 'new_lat'] = df.loc[i, 'lat']
            df.loc[i, 'new_long'] = df.loc[i, 'long']
        else:
            df.loc[i, 'detect_loc'] = 'C'
            df.loc[i, 'new_lat'] = df.loc[i, 'lat'] - delta/2
            df.loc[i, 'new_long'] = df.loc[i, 'long']
    return df

In [30]:
new_inf2 = csv_par3(infers1, 0.0002)

In [31]:
new_inf2

,imgname,class,confidence,xcenter,ycenter,width,hight,lat,long,angle,zipcode,detect_loc,new_lat,new_long
0,39.74879271--105.02297879999999-0.jpg,3,0.436579,0.124219,0.567187,0.045312,0.046875,39.7488,-105.0230,0,80204,L,39.7489,-105.0230
1,39.77412428--105.0159814-0.jpg,2,0.887750,0.415625,0.728906,0.034375,0.064062,39.7741,-105.0160,0,80211,C,39.7740,-105.0160
2,39.77415137--105.01891609999998-0.jpg,0,0.907404,0.450781,0.499219,0.164062,0.557813,39.7742,-105.0189,0,80211,C,39.7741,-105.0189
3,39.77415137--105.01891609999998-0.jpg,2,0.856585,0.860156,0.746094,0.032813,0.054688,39.7742,-105.0189,0,80211,R,39.7742,-105.0189
4,39.763224--105.00516359999999-0.jpg,0,0.878048,0.191406,0.372656,0.267188,0.739062,39.7632,-105.0052,0,80211,L,39.7633,-105.0052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3077,39.73684731--104.9876376-0.jpg,2,0.713935,0.695312,0.665625,0.018750,0.031250,39.7368,-104.9876,0,80264,R,39.7368,-104.9876
3078,39.78216811--105.02622-0.jpg,3,0.503650,0.225781,0.585938,0.020313,0.021875,39.7822,-105.0262,0,80212,L,39.7823,-105.0262
3079,39.751205999999996--105.0249996-0.jpg,0,0.811093,0.076563,0.360156,0.150000,0.464063,39.7512,-105.0250,0,80211,L,39.7513,-105.0250
3080,39.76752569--105.0514081-0.jpg,0,0.616398,0.290625,0.507031,0.059375,0.351562,39.7675,-105.0514,0,80212,L,39.7676,-105.0514
3081,39.72612284--105.0323514-0.jpg,0,0.952682,0.450781,0.437500,0.176563,0.500000,39.7261,-105.0324,0,80219,C,39.7260,-105.0324

In [46]:
#7/5 adjusting coordinates by 'xcenter' position [L, C, R]. 0.013 mile = ~20 meters = 0.0002
# Rachael's version
def csv_par4(df, delta):
    for i in range(len(df)):
        df.loc[i, 'lat'] = float(df.loc[i, 'imgname'].split('-')[0])
        df.loc[i, 'long'] = float(df.loc[i, 'imgname'].split('-')[2]) * -1.0
        df.loc[i, 'angle'] = df.loc[i, 'imgname'].split('-')[3][:-4]
        result = search.by_coordinates(df.loc[i, 'lat'], df.loc[i, 'long'], radius=3)
        df.loc[i, 'zipcode'] = result[0].zipcode
        df.loc[i, 'lat'] = df.loc[i, 'lat'].astype(float).round(4)
        df.loc[i, 'long'] = df.loc[i, 'long'].astype(float).round(4)
        df.loc[i, 'new_lat'] = df.loc[i, 'lat'] + (delta * math.cos((math.pi / 180)*float(df.loc[i, 'angle'])))
        df.loc[i, 'new_long'] = df.loc[i, 'long'] + (delta * math.sin((math.pi / 180)*float(df.loc[i, 'angle'])))
    return df

In [34]:
import math
math.cos(55)

0.022126756261955732

In [40]:
math.cos(362)

-0.7538824495645917

In [41]:
math.pi

3.141592653589793

In [47]:
new_inf3 = csv_par4(infers1, 0.0002)

In [48]:
new_inf3

,imgname,class,confidence,xcenter,ycenter,width,hight,lat,long,angle,zipcode,detect_loc,new_lat,new_long
0,39.74879271--105.02297879999999-0.jpg,3,0.436579,0.124219,0.567187,0.045312,0.046875,39.7488,-105.0230,0,80204,L,39.7490,-105.0230
1,39.77412428--105.0159814-0.jpg,2,0.887750,0.415625,0.728906,0.034375,0.064062,39.7741,-105.0160,0,80211,C,39.7743,-105.0160
2,39.77415137--105.01891609999998-0.jpg,0,0.907404,0.450781,0.499219,0.164062,0.557813,39.7742,-105.0189,0,80211,C,39.7744,-105.0189
3,39.77415137--105.01891609999998-0.jpg,2,0.856585,0.860156,0.746094,0.032813,0.054688,39.7742,-105.0189,0,80211,R,39.7744,-105.0189
4,39.763224--105.00516359999999-0.jpg,0,0.878048,0.191406,0.372656,0.267188,0.739062,39.7632,-105.0052,0,80211,L,39.7634,-105.0052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3077,39.73684731--104.9876376-0.jpg,2,0.713935,0.695312,0.665625,0.018750,0.031250,39.7368,-104.9876,0,80264,R,39.7370,-104.9876
3078,39.78216811--105.02622-0.jpg,3,0.503650,0.225781,0.585938,0.020313,0.021875,39.7822,-105.0262,0,80212,L,39.7824,-105.0262
3079,39.751205999999996--105.0249996-0.jpg,0,0.811093,0.076563,0.360156,0.150000,0.464063,39.7512,-105.0250,0,80211,L,39.7514,-105.0250
3080,39.76752569--105.0514081-0.jpg,0,0.616398,0.290625,0.507031,0.059375,0.351562,39.7675,-105.0514,0,80212,L,39.7677,-105.0514
3081,39.72612284--105.0323514-0.jpg,0,0.952682,0.450781,0.437500,0.176563,0.500000,39.7261,-105.0324,0,80219,C,39.7263,-105.0324